"""add auditable mixin and update documen type

Revision ID: 6a90cb370948
Revises: ec93c161907b
Create Date: 2024-10-16 11:16:37.495213

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a90cb370948'
down_revision = 'ec93c161907b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_types', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('document_types', sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('document_types', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('document_types', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('document_types', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('document_types', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('document_types', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.add_column('document_types', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.add_column('document_types', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.add_column('document_types', sa.Column('visible', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_document_types_abbreviation'), 'document_types', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=True)
    op.create_foreign_key(None, 'document_types', 'users', ['deleted_by_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'document_types', 'users', ['updated_by_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'document_types', 'users', ['created_by_id'], ['user_id'], ondelete='SET NULL')
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('created_by_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('updated_by_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.add_column('documents', sa.Column('visible', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['deleted_by_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['updated_by_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'users', ['created_by_id'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'visible')
    op.drop_column('documents', 'deleted_by_id')
    op.drop_column('documents', 'updated_by_id')
    op.drop_column('documents', 'created_by_id')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.drop_constraint(None, 'document_types', type_='foreignkey')
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_abbreviation'), table_name='document_types')
    op.drop_column('document_types', 'visible')
    op.drop_column('document_types', 'deleted_by_id')
    op.drop_column('document_types', 'updated_by_id')
    op.drop_column('document_types', 'created_by_id')
    op.drop_column('document_types', 'deleted_at')
    op.drop_column('document_types', 'updated_at')
    op.drop_column('document_types', 'created_at')
    op.drop_column('document_types', 'description')
    op.drop_column('document_types', 'abbreviation')
    op.drop_column('document_types', 'name')
    # ### end Alembic commands ###
