"""add app models

Revision ID: ec93c161907b
Revises: 2487b2892907
Create Date: 2024-10-14 21:47:51.035232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ec93c161907b'
down_revision = '2487b2892907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('document_type_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('document_type_id')
    )
    op.create_table('groups',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('abbreviation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_groups_abbreviation'), 'groups', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('codename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('flag', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.create_index(op.f('ix_permissions_flag'), 'permissions', ['flag'], unique=True)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('structures',
    sa.Column('structure_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('structure_id')
    )
    op.create_table('audits',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_type_id', sa.Uuid(), nullable=True),
    sa.Column('structure_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.document_type_id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.structure_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('group_permissions',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('authorizations',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('drafts',
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('document_type_id', sa.Uuid(), nullable=True),
    sa.Column('structure_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.document_type_id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structures.structure_id'], ),
    sa.PrimaryKeyConstraint('draft_id')
    )
    op.create_table('responsibilities',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('draft_attachments',
    sa.Column('draft_attachment_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('draft_attachment_id')
    )
    op.create_table('draft_files',
    sa.Column('draft_file_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('draft_file_id')
    )
    op.create_table('revisions',
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('acceptances',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('assessments',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('draft_attachment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['draft_attachment_id'], ['draft_attachments.draft_attachment_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('change_requests',
    sa.Column('change_request_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('change_request_id')
    )
    op.create_table('copies',
    sa.Column('copy_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('copy_id')
    )
    op.create_table('distributions',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('group_id', 'document_id')
    )
    op.create_table('draft_attachment_files',
    sa.Column('draft_attachment_file_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('draft_attachment_id', sa.Uuid(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['draft_attachment_id'], ['draft_attachments.draft_attachment_id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.draft_id'], ),
    sa.PrimaryKeyConstraint('draft_attachment_file_id')
    )
    op.create_table('revision_files',
    sa.Column('revision_file_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('revision_file_id')
    )
    op.create_table('attachment_files',
    sa.Column('attachment_file_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('attachment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.attachment_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('attachment_file_id')
    )
    op.create_table('change_assessments',
    sa.Column('change_assessment_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.change_request_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('change_assessment_id')
    )
    op.create_table('change_acceptances',
    sa.Column('change_acceptance_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('change_assessment_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_assessment_id'], ['change_assessments.change_assessment_id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.change_request_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('change_acceptance_id')
    )
    op.create_table('changes',
    sa.Column('change_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('old_revision_id', sa.Uuid(), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('change_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('change_acceptance_id', sa.Uuid(), nullable=True),
    sa.Column('new_revision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['change_acceptance_id'], ['change_acceptances.change_acceptance_id'], ),
    sa.ForeignKeyConstraint(['change_assessment_id'], ['change_assessments.change_assessment_id'], ),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_requests.change_request_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['new_revision_id'], ['revisions.revision_id'], ),
    sa.ForeignKeyConstraint(['old_revision_id'], ['revisions.revision_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changes')
    op.drop_table('change_acceptances')
    op.drop_table('change_assessments')
    op.drop_table('attachment_files')
    op.drop_table('revision_files')
    op.drop_table('draft_attachment_files')
    op.drop_table('distributions')
    op.drop_table('copies')
    op.drop_table('change_requests')
    op.drop_table('attachments')
    op.drop_table('assessments')
    op.drop_table('acceptances')
    op.drop_table('revisions')
    op.drop_table('draft_files')
    op.drop_table('draft_attachments')
    op.drop_table('responsibilities')
    op.drop_table('drafts')
    op.drop_table('authorizations')
    op.drop_table('user_permissions')
    op.drop_table('group_permissions')
    op.drop_table('documents')
    op.drop_table('audits')
    op.drop_table('structures')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_flag'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_abbreviation'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('document_types')
    # ### end Alembic commands ###
